### ISSUE TITLE
Browsing folder path results in freeze

### ISSUE THREAD

**Issue by chixxi** [741g/android-emulator-m1-preview#3] opened 2020-12-09 13:56 UTC
Whenever I try to browse to a path in the emulator settings the emulator freezes. This happens on both folder icons for "Screenshot Save Location" and "Use Detected ADB Location".

**Comment by jamescodesthings** [comment] 2020-12-09 14:10
+1 I initially get a warning when opening that adb cannot be automatically detected. When I go to try and change this the emulator app freezes

**Comment by chixxi** [comment] 2020-12-09 15:23
This is on macOS BigSur 11.0.1 20B29 and the emulator version 30.3.2-6992164 (Canary update channel).

**Comment by 741g** [comment] 2020-12-09 21:35
This looks like a Qt bug where it's trying to JIT a regular expression, but in Big Sur, this isn't allowed.

**Comment by 741g** [comment] 2020-12-10 02:37
This should be fixed in release 0.2: https://github.com/741g/android-emulator-m1-preview/releases/tag/0.2

**Comment by chixxi** [comment] 2020-12-10 09:48
I can confirm that this is now working without issues, therefore closing.

**Closed** 2020-12-10 09:48 UTC

**Comment by XTJX21X** [comment] 2020-12-15 22:14
[Edit /Applications/Android\ Emulator.app/Contents/MacOS/aosp-master-arm64-v8a/config.](github.com) 
Duplicate of #

**Comment by XTJX21X** [comment] 2020-12-15 22:14
> $1_$2

**Comment by yibingxiong** [comment] 2021-06-29 12:52
good
